version: '3'
services:
# Nginx Server
  ssl_server:
   build:
     context: ./ssl_server/
   container_name: nginx
   depends_on:
     - web_server
     - cache_server
     - database_server
     - redis_server
     - elastic_server
   volumes:
     - ./ssl_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
     - ./ssl_server/default:/etc/nginx/sites-enabled/default
     - ./ssl_server/nginx.conf:/etc/nginx/nginx.conf
   links:
     - web_server
     - cache_server
     - database_server
     - redis_server
     - elastic_server
   ports: 
     - "80:80"
     - "443:443"
# Redis Server
  redis_server:
    build:
      context: ./redis_server/
    container_name: redis
    depends_on:
      - web_server
      - cache_server
      - database_server
    volumes:
      - ./redis_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    links:
      - web_server
      - database_server 
    #ports:
    #  - "6379:6379"
# Elastic Server
  elastic_server:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      - "discovery.type=single-node"
      ## Set custom heap size to avoid memory errors
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
     # - VIRTUAL_HOST=elastic.sinalite243.com
      - VIRTUAL_PORT=9200
    expose:
      - 9200
# Varnish Server
  cache_server:
    build:
      context: ./cache_server/
    container_name: varnish
    depends_on:
      - web_server
    volumes:
      - ./cache_server/default.vcl:/etc/varnish/default.vcl
      - ./cache_server/varnish:/etc/default/varnish
      - ./cache_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "6081:6081"
      - "6082:6082"
    links:
      - web_server
      - database_server
# Apache2 Server
  web_server:
    build:
      context: ./web_server/
    container_name: apache2
    volumes:
      - ./web_server/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - magento-framework:/var/www/sinalite:nocopy
      - ./web_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "8080:8080"
    links:
      - database_server
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
# MySQL Server      
  database_server:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
      - './sql-db:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_DATABASE: magento
      MYSQL_ROOT_PASSWORD: qazxcde1231
    ports:
      - 3306:3306
# Nodejs API
  flatdesigner_api:
    build: ../flatdesigner_nodejs/
    hostname: api2.sinalite243.com
volumes:
  mysql:
    driver: local
  magento-framework:
    external: true